name: Update RSS feed.

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

  schedule:
    - cron: "0 */4 * * *"

jobs:
  publisher:
    name: Generate feed and upload to GitHub pages.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Generate feed.
        env:
          RF_GITHUB_TOKENS: ${{ secrets.RF_GITHUB_TOKENS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE: ayosec/releasesfeed

        run: ./update.sh
